### PR TITLE
feat: support building multiple mosquitto versions using ziglang 0.15.1

### LINKED ISSUE #5: Update project to support building using ziglang 0.15
Some syntax that is used in the zig build script was deprecated in 0.14 and finally removed in 0.15, resulting in this project now failing to build using ziglang 0.15.

There are some migration notes listed in the ziglang 0.14 release notes that should help with the migration:

* https://ziglang.org/download/0.14.0/release-notes.html#Creating-Artifacts-from-Existing-Modules

**Example build error**

The build error was noticed when building the tedge-standalone project. Below is a snippet taken from the [failed build run](https://github.com/thin-edge/tedge-standalone/actions/runs/18555302292/job/52891237068):

```sh
+ python -m ziglang build -Doptimize=ReleaseSmall -Dtarget=x86_64-linux
build.zig:9:10: error: no field named 'target' in struct 'Build.ExecutableOptions'
        .target = target,
         ^~~~~~
/home/runner/work/tedge-standalone/tedge-standalone/.venv/lib/python3.12/site-packages/ziglang/lib/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_23492: /home/runner/work/tedge-standalone/tedge-standalone/.venv/lib/python3.12/site-packages/ziglang/lib/std/Build.zig:2214:33
    main: /home/runner/work/tedge-standalone/tedge-standalone/.venv/lib/python3.12/site-packages/ziglang/lib/compiler/build_runner.zig:366:29
    5 reference(s) hidden; use '-freference-trace=7' to see all references
error: Recipe `build` failed on line 6 with exit code 2
```

### PR DESCRIPTION
**Pull request by reubenmiller**
Support building multiple mosquitto versions:

* Support building multiple mosquitto versions (project has been restructured to have multiple build.zig files now)
  * 2.0.18, 2.0.22 and 2.1.0-develop (from the mosquitto's develop branch)
* Download mosquitto source code via zig dependencies (e.g. in the build.zig.zon file)
* Update openssl from 3.4.0 to 3.6.0
* Update build.zig syntax to be compatible with ziglang 0.15.1 (resolves #5)
* New github workflow to check that building multiple mosquitto versions works

Note: mosquitto 2.0.23 will be released very shortly, and this PR has already been validated against the "master" (main) branch of mosquitto. Once the version is official released then the default version built will be changed to 2.0.23 as it included a vital fix as referenced in https://github.com/thin-edge/thin-edge.io/issues/3185

### CODE REVIEW

**Review by didier-wenzek — APPROVED** [review]
Approved.

However to `just` build it, I have to update the `justfile` replacing all the occurrence of `env`.

```
- VERSION := env("VERSION", "2.0.22-1")
+ VERSION := env_var_or_default("VERSION", "2.0.22-1")
```

**Comment by reubenmiller** [comment]
> Approved.
> 
> However to `just` build it, I have to update the `justfile` replacing all the occurrence of `env`.
> 
> ```
> - VERSION := env("VERSION", "2.0.22-1")
> + VERSION := env_var_or_default("VERSION", "2.0.22-1")
> ```

You should update your just binary (>= 1.15.0) as that function has been deprecated in newer versions, see the [notice](https://github.com/casey/just?tab=readme-ov-file#environment-variables)

Though I'll add just to the build dependency list (including the required version).

**Comment by reubenmiller** [comment]
[560b780](https://github.com/thin-edge/zig-mosquitto/pull/6/commits/560b7804be3dbc791577fec4b444d38d99a75dfb) adds just to the build dependency list

**Review by didier-wenzek — APPROVED** [review]
I confirm my approval. This works nicely.
