### ISSUE TITLE
Update project to support building using ziglang 0.15

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/zig-mosquitto#5]
Some syntax that is used in the zig build script was deprecated in 0.14 and finally removed in 0.15, resulting in this project now failing to build using ziglang 0.15.

There are some migration notes listed in the ziglang 0.14 release notes that should help with the migration:

* https://ziglang.org/download/0.14.0/release-notes.html#Creating-Artifacts-from-Existing-Modules

**Example build error**

The build error was noticed when building the tedge-standalone project. Below is a snippet taken from the [failed build run](https://github.com/thin-edge/tedge-standalone/actions/runs/18555302292/job/52891237068):

```sh
+ python -m ziglang build -Doptimize=ReleaseSmall -Dtarget=x86_64-linux
build.zig:9:10: error: no field named 'target' in struct 'Build.ExecutableOptions'
        .target = target,
         ^~~~~~
/home/runner/work/tedge-standalone/tedge-standalone/.venv/lib/python3.12/site-packages/ziglang/lib/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_23492: /home/runner/work/tedge-standalone/tedge-standalone/.venv/lib/python3.12/site-packages/ziglang/lib/std/Build.zig:2214:33
    main: /home/runner/work/tedge-standalone/tedge-standalone/.venv/lib/python3.12/site-packages/ziglang/lib/compiler/build_runner.zig:366:29
    5 reference(s) hidden; use '-freference-trace=7' to see all references
error: Recipe `build` failed on line 6 with exit code 2
```

**Comment by reubenmiller** [comment]
Unfortunately this change is going to be more complicated as openssl also needs to be updated (when building with tls at least).

Also, newer versions of mosquitto seem to have some project changes which adds a few dependencies (e.g. cJSON), which will also require a few other changes...so parking this topic for now.
